### ISSUE TITLE
Google Map to show where people came from

### ISSUE THREAD

**Issue by sethetter** [openwichita/project-ideas-old#10]
An interactive Google Map that let's people mark where they came from to visit the Open Streets event.

This would let us show things like "how far did people travel" to attend. It also is just a generally cool visualization to show the movement of people.

People could either enter an address (might feel weird about that), or touch a spot on a map.

The visualization could take all of the spots and draw lines from them to the Open Streets grounds.

**Comment by infernocloud** [comment]
This issue was moved to openwichita/project-ideas#2
