### ISSUE TITLE
Historic walk of Douglas Ave

### ISSUE THREAD

**Issue by sethetter** [openwichita/project-ideas-old#9]
The idea is to have a mobile application or website that can detect when you are at certain points along the Open Streets event and prompt you with interesting historic information about that spot.

* Old photos
* Things that used to be or had happened there
* Stats about Wichita during those times
* etc etc etc

Could be done with geofencing, bluetooth beacons, QR codes, or a number of other ways.

Anyone interested in making this happen?

**Comment by infernocloud** [comment]
This issue was moved to openwichita/project-ideas#3
